server:
    contextPath: /mps

datasource:
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sqlserver://mssqlhost:1433/mypractice;
    username: sa
    password: Qwerty123

spring:
    jpa:
        database: SQL_SERVER
        show-sql: true

liquibase:
    enabled: false
