server:
    contextPath: /mps

datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:cqs

spring:
    jpa:
        database: H2
        show-sql: true

liquibase:
    changeLog: classpath:/db/changelog-master.xml
